-- SQL Script to insert 4 wireless mice into the products table
-- You can run this directly in the Supabase SQL Editor

INSERT INTO public.products (
  name, 
  slug, 
  description, 
  expert_note, 
  price_range, 
  affiliate_link, 
  brand, 
  marketplace,
  seo_title,
  seo_description,
  pros,
  cons,
  buying_verdict,
  smart_score,
  value_score,
  approval_status
) VALUES 
(
  'ZEBRONICS Glassy 10 Wireless Mouse',
  'zebronics-glassy-10-wireless-mouse',
  'Dual Mode (2.4GHz + BT) wireless mouse featuring up to 1600 DPI, silent operation, and Type-C charging. Ergonomic design suitable for Mac and PC.',
  'A visually striking, transparent budget mouse that offers versatile dual-mode connectivity and the convenience of Type-C recharging.',
  'Under ₹1000',
  'https://www.amazon.in/ZEBRONICS-Wireless-Operation-Comfortable-Ergonomic/dp/B0F88GT83S/',
  'ZEBRONICS',
  'Amazon',
  'ZEBRONICS Glassy 10 Wireless Mouse - Dual Mode & Type-C',
  'Buy ZEBRONICS Glassy 10 Wireless Mouse with dual mode, silent operation, and Type-C charging.',
  '["Dual connectivity (BT+2.4GHz)", "Rechargeable via Type-C", "Silent clicks", "Unique transparent aesthetic"]',
  '["Build quality may feel plasticky to some", "Battery capacity is modest compared to AA alternatives"]',
  'Great value for users wanting a stylish, dual-mode rechargeable mouse on a tight budget.',
  8.0,
  8.5,
  'published'
),
(
  'Portronics Toad 23 Wireless Optical Mouse',
  'portronics-toad-23-wireless-mouse',
  'A straightforward 2.4GHz wireless optical mouse with USB Nano Dongle, adjustable DPI, and ergonomic click wheel.',
  'A no-frills, reliable basic wireless mouse perfect for everyday office tasks and budget-conscious buyers.',
  'Under ₹500',
  'https://www.amazon.in/gp/aw/d/B0B296NTFV/',
  'Portronics',
  'Amazon',
  'Portronics Toad 23 Wireless Optical Mouse',
  'Shop Portronics Toad 23 Wireless Mouse. Affordable, reliable 2.4GHz optical mouse.',
  '["Extremely affordable", "Plug and play simplicity", "Adjustable DPI"]',
  '["Basic design", "Lacks Bluetooth connectivity", "Not ideal for gaming"]',
  'A solid, ultra-budget pick for standard daily usage.',
  7.0,
  9.0,
  'published'
),
(
  'Logitech M221 Wireless Mouse',
  'logitech-m221-silent-wireless-mouse',
  'Silent buttons, 2.4 GHz wireless connection with USB Mini Receiver, 1000 DPI Optical Tracking, and up to 18-Month Battery Life.',
  'The gold standard for quiet workspaces. It delivers Logitech''s renowned reliability with a truly silent click mechanism.',
  '₹500 - ₹1000',
  'https://www.amazon.in/Logitech-Silent-Wireless-Mouse-Charcoal/dp/B01M72LILF/',
  'Logitech',
  'Amazon',
  'Logitech M221 Silent Wireless Mouse - Charcoal Grey',
  'Get the Logitech M221 Silent Wireless Mouse for a quiet, reliable experience with 18-month battery life.',
  '["Over 90% noise reduction", "18-month battery life", "Reliable Logitech build", "Compact and portable"]',
  '["A bit small for larger hands", "No Bluetooth option"]',
  'The best choice for anyone working in a quiet office, library, or shared space.',
  9.0,
  8.5,
  'published'
),
(
  'Logitech M186 Wireless Mouse',
  'logitech-m186-wireless-mouse',
  '2.4GHz with USB Mini Receiver, 1000 DPI Optical Tracking, Ambidextrous design, and up to 3 Years Battery Life.',
  'An absolute workhorse. Known for its insane battery life and durability, making it one of the most practical mice available.',
  '₹500 - ₹1000',
  'https://www.amazon.in/Logitech-Wireless-Receiver-Ambidextrous-Compatible/dp/B0D18192T2/',
  'Logitech',
  'Amazon',
  'Logitech M186 Wireless Mouse - 3 Years Battery Life',
  'Logitech M186 offers reliable 2.4GHz wireless tracking and an incredible 3-year battery life.',
  '["Incredible 3-year battery life", "Very durable build", "Ambidextrous design", "Great value"]',
  '["Basic aesthetics", "Clicks are not silent"]',
  'Perfect for users who want to plug in a mouse and forget about changing batteries for years.',
  8.5,
  9.0,
  'published'
);
